# Generated by Django 4.2.24 on 2025-09-11 22:18

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the withdrawal request', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount to withdraw', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_method', models.CharField(choices=[('paypal', 'PayPal'), ('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer'), ('bitcoin', 'Bitcoin'), ('other', 'Other')], help_text='Preferred payment method', max_length=10)),
                ('payment_details', models.TextField(help_text='Payment details (email, phone, account number, etc.)')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('processing', 'Processing Payment'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of withdrawal request', max_length=15)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes from admin processing')),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (if applicable)')),
                ('external_transaction_id', models.CharField(blank=True, help_text='Transaction ID from payment processor', max_length=100)),
                ('fee_charged', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Processing fee charged (if any)', max_digits=10)),
                ('amount_sent', models.DecimalField(blank=True, decimal_places=2, help_text='Actual amount sent to user (after fees)', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User requesting withdrawal', on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Withdrawal Request',
                'verbose_name_plural': 'Withdrawal Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the transaction', primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('survey_payment', 'Survey Payment'), ('withdrawal', 'Withdrawal'), ('bonus', 'Bonus Payment'), ('refund', 'Refund'), ('adjustment', 'Balance Adjustment')], help_text='Type of transaction', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='completed', help_text='Transaction status', max_length=10)),
                ('description', models.CharField(help_text='Description of the transaction', max_length=255)),
                ('balance_before', models.DecimalField(decimal_places=2, help_text='User balance before this transaction', max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='User balance after this transaction', max_digits=10)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this transaction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(blank=True, help_text='Admin user who processed this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_transactions', to=settings.AUTH_USER_MODEL)),
                ('survey_response', models.ForeignKey(blank=True, help_text='Survey response that generated this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, to='surveys.response')),
                ('user', models.ForeignKey(help_text='User this transaction belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('withdrawal_request', models.ForeignKey(blank=True, help_text='Withdrawal request associated with this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.withdrawalrequest')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the payment method', primary_key=True, serialize=False)),
                ('method_type', models.CharField(choices=[('paypal', 'PayPal'), ('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer'), ('bitcoin', 'Bitcoin'), ('other', 'Other')], help_text='Type of payment method', max_length=10)),
                ('account_name', models.CharField(help_text='Account holder name', max_length=100)),
                ('account_details', models.TextField(help_text='Account details (email, phone, account number, etc.)')),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default payment method')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether this payment method has been verified')),
                ('verification_notes', models.TextField(blank=True, help_text='Admin notes about verification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(help_text='User this payment method belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, help_text='Admin who verified this payment method', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
