# Generated by Django 4.2.24 on 2025-09-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_mpesatransaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('registration', 'Registration Payment'), ('survey_payment', 'Survey Payment'), ('withdrawal', 'Withdrawal'), ('adjustment', 'Admin Adjustment'), ('bonus', 'Bonus Payment'), ('refund', 'Refund'), ('fee', 'Fee Deduction')], max_length=20),
        ),
    ]
