# Generated by Django 4.2.24 on 2025-09-14 21:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, default='Kenya', help_text="User's country", max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='mpesa_checkout_request_id',
            field=models.CharField(blank=True, help_text='M-Pesa checkout request ID for tracking', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mpesa_receipt_number',
            field=models.CharField(blank=True, help_text='M-Pesa receipt number for registration payment', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('500.00'), help_text='Registration fee amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_paid',
            field=models.BooleanField(default=False, help_text='Whether user has paid the registration fee'),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_payment_date',
            field=models.DateTimeField(blank=True, help_text='When the registration payment was completed', null=True),
        ),
    ]
