# Generated by Django 4.2.24 on 2025-09-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_referral_system'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='referralcommission',
            new_name='accounts_re_referre_185846_idx',
            old_name='accounts_re_referre_f8b9a3_idx',
        ),
        migrations.RenameIndex(
            model_name='referralcommission',
            new_name='accounts_re_process_0aca74_idx',
            old_name='accounts_re_process_c75e9a_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, help_text='Unique referral code for this user', max_length=10, unique=True),
        ),
    ]
