# Generated by Django 4.2.24 on 2025-09-19 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_accounts_re_referre_f8b9a3_idx_accounts_re_referre_185846_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('setting_key', models.CharField(help_text='Unique identifier for this setting', max_length=100, unique=True)),
                ('setting_name', models.CharField(help_text='Human-readable name', max_length=200)),
                ('setting_type', models.CharField(choices=[('fee', 'Fee Amount'), ('rate', 'Commission Rate'), ('limit', 'System Limit'), ('config', 'Configuration')], default='config', max_length=20)),
                ('decimal_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('integer_value', models.IntegerField(blank=True, null=True)),
                ('text_value', models.TextField(blank=True, null=True)),
                ('boolean_value', models.BooleanField(blank=True, null=True)),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum allowed value (for numeric settings)', max_digits=10, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum allowed value (for numeric settings)', max_digits=10, null=True)),
                ('description', models.TextField(help_text='Description of what this setting controls')),
                ('is_active', models.BooleanField(default=True)),
                ('requires_restart', models.BooleanField(default=False, help_text='Whether changing this requires app restart')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
                'ordering': ['setting_name'],
            },
        ),
        migrations.CreateModel(
            name='SettingsAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('change_reason', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='accounts.systemsettings')),
            ],
            options={
                'verbose_name': 'Settings Audit Log',
                'verbose_name_plural': 'Settings Audit Logs',
                'ordering': ['-changed_at'],
            },
        ),
    ]
