# Generated by Django 4.2.24 on 2025-09-13 11:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False, help_text='Mark this choice as a correct answer'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text Answer (Short)'), ('textarea', 'Textarea (Long Answer)'), ('mcq', 'Multiple Choice'), ('checkbox', 'Checkbox (Multiple Select)'), ('rating', 'Rating Scale'), ('yes_no', 'Yes/No')], default='mcq', help_text='Type of question', max_length=10),
        ),
    ]
