# Generated by Django 4.2.24 on 2025-09-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_choice_created_at_choice_is_correct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='completed',
            field=models.BooleanField(default=False, help_text='Whether this response has been completed'),
        ),
    ]
