# Generated by Django 4.2.24 on 2025-09-22 14:13

import django.core.validators
from django.db import migrations, models
import tutorials.models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizanswer',
            old_name='answer_text',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='quizquestion',
            old_name='question_text',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='tutorial',
            old_name='quiz_pass_percentage',
            new_name='quiz_passing_score',
        ),
        migrations.RenameField(
            model_name='usertutorialprogress',
            old_name='quiz_passed',
            new_name='is_passed',
        ),
        migrations.RenameField(
            model_name='usertutorialprogress',
            old_name='best_quiz_score',
            new_name='score_percentage',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='quiz_required',
            field=models.BooleanField(default=False, help_text='Require quiz completion for tutorial'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload video file (MP4, WebM, AVI, MOV, MKV - Max 500MB)', null=True, upload_to=tutorials.models.tutorial_video_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'avi', 'mov', 'mkv'])]),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='video_source',
            field=models.CharField(choices=[('url', 'External URL'), ('upload', 'Uploaded File')], default='url', help_text='Source of the video content', max_length=10),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube, Vimeo, or direct video URL', null=True),
        ),
    ]
