# Generated by Django 4.2.24 on 2025-09-22 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_alter_tutorial_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Optional category for organizing tutorials', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutorials', to='tutorials.tutorialcategory'),
        ),
    ]
